### ISSUE TITLE
Possibly crashing when unable to reach keen.io

### ISSUE THREAD

**Issue by chesleybrown** [sebinsua/express-keenio#36]
I'm not positive on this, but I believe when it's unable to hit keen.io it seems to throw an exception. Is this intended? And if so how should I go about catching this error to prevent it from crashing the running application?

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
```

**Comment by sebinsua** [comment]
Definitely not intended. Will take a look when I get back home.

**Comment by sebinsua** [comment]
Should be fixed now. Sorry about that! Not sure how I did not notice the default behaviour being so bad...

**Comment by chesleybrown** [comment]
Sweet! Thank you, thank you! :smile_cat:
