### ISSUE TITLE
Collection name is invalid

### ISSUE THREAD

**Issue by chesleybrown** [sebinsua/express-keenio#39]
Sorry to bring bad news again... Since updating, I'm no longer getting the issue from #36 anymore, however I'm getting these fairly random crashes now. My current setup is pretty basic, just using the defaults right now

```js
keenio.configure({
	client: settings.keenio
});
server.use(keenio.handleAll());
```

Below is the random crash I'm experiencing.

```
Error from express-keenio not handled with .on('error'): Error: Collection name is invalid. Must be <= 64 characters, cannot contain a newline or CR.It also cannot contain non-ascii characters. You specified: 'get-post-put-head-delete-options-trace-copy-lock-mkcol-move-purge-propfind-proppatch-unlock-report-mkactivity-checkout-merge-m-search-notify-subscribe-unsubscribe-patch-search-connect-*'.
    at module.exports (/mnt/data/2/node_modules/express-keenio/node_modules/keen-js/src/core/helpers/superagent-handle-response.js:5:49)
    at handleResponse (/mnt/data/2/node_modules/express-keenio/node_modules/keen-js/src/core/lib/addEvent.js:88:5)
    at Request.callback (/mnt/data/2/node_modules/express-keenio/node_modules/keen-js/node_modules/superagent/lib/node/index.js:746:30)
    at Request.<anonymous> (/mnt/data/2/node_modules/express-keenio/node_modules/keen-js/node_modules/superagent/lib/node/index.js:135:10)
    at Request.emit (events.js:95:17)
    at Stream.<anonymous> (/mnt/data/2/node_modules/express-keenio/node_modules/keen-js/node_modules/superagent/lib/node/index.js:938:12)
    at Stream.emit (events.js:117:20)
    at Unzip.<anonymous> (/mnt/data/2/node_modules/express-keenio/node_modules/keen-js/node_modules/superagent/lib/node/utils.js:124:12)
    at Unzip.emit (events.js:117:20)
    at _stream_readable.js:944:16
```

**Comment by sebinsua** [comment]
I'll take a look at this.

Do you know what route it is that causes this to happen?

I think it's [this line in my code](https://github.com/sebinsua/express-keenio/blob/master/lib/event-collection.js#L15). I am wondering if for some reason the route.methods is coming through with more than just `{ GET: true }` (etc.) as it seems to create a huge list of methods.

Either way, I will truncate - but I might create another more compact representation if what is passed is extremely large: it shouldn't be possible to generate a name which doesn't pass validation.

**Comment by sebinsua** [comment]
Did 0.4.1 fix it?

I'd still like to know what route is creating that super super long event collection name. I can't see how it's happening as route.methods should only ever contain just a key-value of methods, and likewise route.path should never be too long.

**Comment by chesleybrown** [comment]
Hey, sorry for the slow response.

The longest API call I currently have looks like this:

https://api.rentchek.com/receipt/preview?property={%22_id%22%3A%225439448dcd8e84e5b436073e%22%2C%22user_id%22%3A%22507f1f77bcf86cd799439011%22%2C%22rent%22%3A1600%2C%22address%22%3A%22189%20Prescott%20St.%22%2C%22city%22%3A%22St.%20John%27s%22%2C%22country%22%3A%22Canada%22%2C%22province%22%3A%22Newfoundland%22%2C%22postal%22%3A%22A1C3S4%22%2C%22tenants%22%3A[{%22_id%22%3A%2254628c510221b6000004f946%22%2C%22name%22%3A%22Jimmy%20Car%22%2C%22email%22%3A%22jimmy%40example.com%22%2C%22phone%22%3Anull%2C%22deposit%22%3Anull%2C%22start%22%3A%222014-10-01T02%3A30%3A00.000Z%22%2C%22end%22%3Anull}]%2C%22created%22%3A%222014-02-01T04%3A30%3A00.000Z%22%2C%22updated%22%3Anull%2C%22%24%24hashKey%22%3A%22object%3A70%22}&landlord={%22_id%22%3A%22507f1f77bcf86cd799439011%22%2C%22email%22%3A%22chesley%40example.com%22%2C%22name%22%3A%22Chesley%20Brown%22}&type=rent&tenant={%22_id%22%3A%2254628c510221b6000004f946%22%2C%22name%22%3A%22Jimmy%20Car%22%2C%22email%22%3A%22jimmy%40example.com%22%2C%22phone%22%3Anull%2C%22deposit%22%3Anull%2C%22start%22%3A%222014-10-01T02%3A30%3A00.000Z%22%2C%22end%22%3Anull}&amount=1600&date=2015-03-15T08%3A40%3A39-02%3A30

So if there is a limit on keenio's side, I can certainly see that endpoint crossing it. lol

I will try `0.4.1` now and see if the error happens anymore.

While I was checking for this error I also came across another one, but I'll log that as another issue as it's completely separate from this one.

**Comment by chesleybrown** [comment]
Seething this in my log now.

```
WARNING: The string found at property (reaction) is huge and has been smited.
```

Better than an error :smile: lol

**Comment by sebinsua** [comment]
Ah, I will remove the warnings from the error logging.

**Comment by chesleybrown** [comment]
Yeah. Good idea. My log is just filled with the warnings now. lol

Maybe have a logging flag to enable such messages?

**Comment by sebinsua** [comment]
Okay, there should be another version now (0.4.3).

I don't actually log directly with console.log. I normally emit an event that is like 'error' and by default it has `console.warn` against it. I have put the warnings against the event 'debug'.

If you wish to change how these events are handled you can:

```
keenio.on('error', function (message) {
    // Your code goes here.
});
keenio.on('debug', function (message) {
    // Your code goes here.
});
```

However hopefully the default behaviour is better now and you will not need to do this. :)

**Comment by chesleybrown** [comment]
Nice, that's a great idea. Confirmed I'm no longer seeing the warnings in my logs by default. Thanks :+1:
